### ISSUE TITLE
Add HACS support

### ISSUE THREAD

**Issue by T-REX-XP** [billhu1996/SynologySwitch#1]
Hi! Can you please add Hacs.xy marketplace support I have got an issue during the adding to the custom repositories:
 - Exception: HacsException
Message: Repostitory structure for master is not compliant
Could not add this repository, make sure it is compliant with HACS.

**Comment by billhu1996** [comment]
No problem!
Thank you for introducing me this good tool (HACS). I will install HACS and connect my custom_components to HACS.
I am busy, but I will take time to access this.

**Comment by T-REX-XP** [comment]
One more question. Can you try to build custom component that will turn on the home mode in the survival station ? If will be very useful. Thanks.

**Comment by billhu1996** [comment]
Sorry. I don't need this feature, so I won't develop it with high probability.
However, you can develop based on SynologySwitch, and SynologySwitch welcome PR.

**Comment by billhu1996** [comment]
Supported
