### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by lollox80** [billhu1996/SynologySwitch#2]
In the log I have  some warning messages:

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for synology doing I/O at custom_components/synology/switch.py, line 96: resp = requests.get(self.url + "/webman/index.cgi", timeout=self.timeout, verify=self.secure)

**Comment by billmatxas** [comment]
Thanks for your submission, I will try to fix it.
