### ISSUE TITLE
No 'version' key Error

### ISSUE THREAD

**Issue by MariuszTr** [billhu1996/SynologySwitch#3]
Logger: homeassistant.loader
Source: loader.py:794
First occurred: 21 maja 2021, 11:42:28 (1 occurrences)
Last logged: 21 maja 2021, 11:42:28

No 'version' key in the manifest file for custom integration 'synology_switch'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'synology_switch'

**Comment by billhu1996** [comment]
Fixed.

Thanks.
